# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0003_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
